[postgres]
dbname = "sales_dashboard_db"
user = "postgres"
password = "Next2025" # Replace with your actual password
host = "localhost" # Or your PostgreSQL server's host if it's not local
port = "5432"